### PR TITLE
Update actions/environments to recent versions:

### PR DESCRIPTION
**Pull request by DanielKotik**
Update workflow files to avoid using features and environments that will soon become deprecated.

### CODE REVIEW

**Comment by DanielKotik** [comment]
The tests fails due to an installation issue:

image

It seems that `pipenv` is using Python 3.10 instead of Python 3.8. Not yet sure why...

**Comment by DanielKotik** [comment]
> The tests fail due to an installation issue:
> 
> image
> 
> It seems that `pipenv` is using Python 3.10 instead of Python 3.8. Not yet sure why...

Fixed.

**Review by timcallow — APPROVED** [review]

**Comment by timcallow** [comment]
> The tests fail due to an installation issue:
> 
> image
> 
> It seems that `pipenv` is using Python 3.10 instead of Python 3.8. Not yet sure why...

Maybe just because Ubuntu 22.04 uses Python 3.10 by default

**Comment by DanielKotik** [comment]
> > The tests fail due to an installation issue:
> > image
> > It seems that `pipenv` is using Python 3.10 instead of Python 3.8. Not yet sure why...
> 
> Maybe just because Ubuntu 22.04 uses Python 3.10 by default

Yes, you're right. Nonetheless, this puzzles me as it reads from the `setup-python` actions [README](https://github.com/actions/setup-python):

Yes, you are right. Nevertheless, this confuses me because the  [README](https://github.com/actions/setup-python) of  action `setup-python` says:

>This action provides the following functionality for GitHub Actions users:
    - Installing a version of Python or PyPy and (by default) adding it to the PATH
    - Optionally caching dependencies for pip, pipenv and poetry

I get around this problem by explicitly specifying the python version to use along with pipenv...

**Pull request merged**
