### PR TITLE
Finalize docs

### PR DESCRIPTION
**Pull request by DanielKotik**
I have added a section with build instructions for the documentation (for doing it locally), added a `requirements.txt` for docs dependencies and fixed remaining errors in `conf.py`. With these changes, we are ready to move on to setup the docs CI pipeline.

### CODE REVIEW

**Comment by timcallow** [comment]
Looks good.

I think the docstring in `models.py.ISModel` is not rendering correctly due to some incorrect formatting... But even if it were rendering there would the same error as we saw in PRs #17 and #16. I will fix later today.

**Comment by DanielKotik** [comment]
> Looks good.
> 
> I think the docstring in `models.ISModel` is not rendering correctly due to some incorrect formatting... But even if it were rendering there would the same error as we saw in PRs #18 and #16. I will fix later today.

Mhh, for me this docsting looks good. Also, there are now warning messages anymore.

**Comment by timcallow** [comment]
> > Looks good.
> > I think the docstring in `models.ISModel` is not rendering correctly due to some incorrect formatting... But even if it were rendering there would the same error as we saw in PRs #18 and #16. I will fix later today.
> 
> Mhh, for me this docsting looks good. Also, there are now warning messages anymore.

Strange there are no warnings, but I don't see any of the class parameters displaying? And the `property`s have no docs

Screenshot from 2021-06-28 12-02-10

**Comment by DanielKotik** [comment]
> > > Looks good.
> > > I think the docstring in `models.ISModel` is not rendering correctly due to some incorrect formatting... But even if it were rendering there would the same error as we saw in PRs #18 and #16. I will fix later today.
> > 
> > 
> > Mhh, for me this docsting looks good. Also, there are now warning messages anymore.
> 
> Strange there are no warnings, but I don't see any of the class parameters displaying? And the `property`s have no docs


@timcallow Please follow these steps and report if the issues your mention persist:
```sh
cd docs
python3 -m venv docs-env
source docs-env/bin/activate
pip install -U pip
pip install -r requirements.txt
make clean
make apidocs
make html
```

**Comment by timcallow** [comment]
@DanielKotik I did try these steps but the problem above persists.

To be clear `make html` does not raise any actual errors, but you can see from my screenshot that the `ISModel` `Parameters` are not shown (and the `property`s also missing docstrings). Maybe it's not the case for you somehow?

**Comment by timcallow** [comment]
> @DanielKotik I did try these steps but the problem above persists.
> 
> To be clear `make html` does not raise any actual errors, but you can see from my screenshot that the `ISModel` `Parameters` are not shown (and the `property`s also missing docstrings). Maybe it's not the case for you somehow?

Anyway it's a simple fix, I'll do it later

**Comment by DanielKotik** [comment]
> > @DanielKotik I did try these steps but the problem above persists.
> > To be clear `make html` does not raise any actual errors, but you can see from my screenshot that the `ISModel` `Parameters` are not shown (and the `property`s also missing docstrings). Maybe it's not the case for you somehow?
> 
> Anyway it's a simple fix, I'll do it later

Ahh, now I get it. The docstring of the `__init__` method is not rendered at all. I was just wondering, that your properties are somehow grouped together. Anyway, we need to fix this. Also the parameter and attribute list seems not to correctly reflecty the constructor signature (e.g. `atom` is missing).

**Comment by DanielKotik** [comment]
@timcallow Please have a look at https://stackoverflow.com/questions/5599254/how-to-use-sphinxs-autodoc-to-document-a-classs-init-self-method 
It seems that constructor methods do not get parsed an rendered by Sphinx autodoc by default. Let us first merge this PR, make a dedicated issue (I will do that) and fix it on a dedicated branch.

**Comment by timcallow** [comment]
> @timcallow Please have a look at https://stackoverflow.com/questions/5599254/how-to-use-sphinxs-autodoc-to-document-a-classs-init-self-method
> It seems that constructor methods do not get parsed an rendered by Sphinx' autodoc by default. Let us first merge this PR, make a dedicated issue (I will do that -> #26 ) and fix it on a dedicated branch.

Ok, I merge this PR now. See my comment on #26

**Pull request merged**
